# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/vivalto3gvn/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/vivalto3gvn/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/vivalto3gvn/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/vivalto3gvn/proprietary/bin/bmgr:system/bin/bmgr \
    vendor/samsung/vivalto3gvn/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/vivalto3gvn/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/vivalto3gvn/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/vivalto3gvn/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/vivalto3gvn/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/vivalto3gvn/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/vivalto3gvn/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/audio.primary.scx15.so:system/lib/hw/audio.primary.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/camera.scx15.so:system/lib/hw/camera.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/camera2.scx15.so:system/lib/hw/camera2.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/sensors.scx15.so:system/lib/hw/sensors.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/sprd_gsp.scx15.so:system/lib/hw/sprd_gsp.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/gralloc.scx15.so:system/lib/hw/gralloc.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/hwcomposer.scx15.so:system/lib/hw/hwcomposer.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libaudiosa.so:system/lib/libaudiosa.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungearcare.so:system/lib/libsamsungearcare.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungeffect.so:system/lib/libsamsungeffect.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libSamsungPkcs11Wrapper.so:system/lib/libSamsungPkcs11Wrapper.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_SamsungRec_V03011b.so:system/lib/lib_SamsungRec_V03011b.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsamsungtts.so:system/lib/libsamsungtts.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libmtp_samsung.so:system/lib/libmtp_samsung.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libmtp_samsung_jni.so:system/lib/libmtp_samsung_jni.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libcutils.so:system/lib/libcutils.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libseccamera_jni.so:system/lib/libseccamera_jni.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsonivox.so:system/lib/libsonivox.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:system/lib/lib_SoundAlive_SRC192_ver205.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/lib_SoundAlive_ver118t.so:system/lib/lib_SoundAlive_ver118t.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libusbhost.so:system/lib/libusbhost.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libEGL.so:system/lib/libEGL.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libETC1.so:system/lib/libETC1.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libGLESv3.so:system/lib/libGLESv3.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libOpenMAXAL.so:system/lib/libOpenMAXAL.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libOpenSLES.so:system/lib/libOpenSLES.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_aacdec_sprd.so:system/lib/libomx_aacdec_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_mp3dec_sprd.so:system/lib/libomx_mp3dec_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/modules/mali.ko:system/lib/modules/mali.ko \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_mpeg4enc.so:system/lib/libstagefright_sprd_mpeg4enc.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_h264dec.so:system/lib/libstagefright_sprd_h264dec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libmorpho_facesolid.so:system/lib/libmorpho_facesolid.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libstagefright_sprd_vpxdec.so:system/lib/libstagefright_sprd_vpxdec.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/camera2.scx15.so:system/lib/hw/camera2.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/hw/camera.scx15.so:system/lib/hw/camera.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/vivalto3gvn/proprietary/vendor/lib/hw/lights.scx15.so:system/vendor/lib/hw/lights.scx15.so \
    vendor/samsung/vivalto3gvn/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so
